### PR TITLE
fix(Linux): Summons properly on linux

### LINKED ISSUE #56: Toggle on Linux doesn't work properly
- [x] I am on the [latest](https://github.com/soutar/hyperterm-summon/releases/latest) hyperterm-summon version
- [x] I have searched the [issues](https://github.com/soutar/hyperterm-summon/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Manjaro Linux using KDE
- **Hyper.app version**: 3.0.2
- **hyperterm-summon version**: 2.0.9
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/jcrben/3ee156917cc4d5ea4e25d66e1d74e6b7
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: 

---

## Issue

When Hyper is visible in the taskbar, it doesn't toggle. This means that for the toggling to work, I have to make sure to toggle it so that it is hidden before switching to another window.

### Steps to Reproduce

Toggle Hyper to show it. Then click on an app in the taskbar. Then try to toggle Hyper to make it pop up and notice that it doesn't work.

image

Note that I loaded this up in dev and it worked properly from development, but I ran into another issue w/ one of my keyboard shortcuts breaking https://spectrum.chat/zeit/hyper/debugging-advice-keymap-not-firing-in-dev~c9595898-a74a-4b65-a10f-a26eaf2f8a37.

### PR DESCRIPTION
**Pull request by dac09**
Fixes #56, with a caveat - hideOnBlur gets over-ridden to true on linux.

I've spent the past few hours on this, very difficult issue to replicate in dev mode, because the issue doesn't quite occur the same way when running hyper in dev mode.

I've annotated with comments in the code, but some useful things I found in the process:
- If you want to replicate the issue in dev mode, use window.blur() and you'll notice both isFocused and isVisible report as true - which is why summon tries to hide the (already hidden) window.
- I tried hooking into the window focus/blur events with separate functions, and setting a boolean in a singleton, which fixed it in dev, but not on prod! I think for some reason blurring in prod-mode means it just doesn't trigger the shortcut

### CODE REVIEW

**Comment by dac09** [comment]
Please review on mac @dcalhoun - I don't use hyper on mac normally, but I'll give it a try in the morning too and report back.

File: modules/app.js [hunk 1]
```diff
@@ -17,7 +17,9 @@ const applyConfig = (app, handleBlur) => {
     config.hideDock ? app.dock.hide() : app.dock.show();
   }
 
-  if (!config.hideOnBlur) {
+  // Linux handles blurs strangely
+  // override hideOnBlur to true here, so summon atleast works!
```
Comment (dcalhoun) [inline modules/app.js:21]:
```suggestion
  // override hideOnBlur to true here, so summon at least works!
```

File: package.json [hunk 2]
```diff
@@ -1,6 +1,6 @@
 {
   "name": "hyperterm-summon",
-  "version": "2.0.9",
+  "version": "2.0.10",
```
Comment (dcalhoun) [inline package.json:3]: Please revert this change. I'll handle a version bump with the release command for this package.

**Comment by dac09** [comment]
> I ran your branch locally and macOS appeared to be working correctly. Will you be willing to add tests for the Linux issues you are addressing?

Sure I'll look into the tests later this week :)
 
> Thank you for helping with this issue!

No probs, thank you for building this in the first place! Happy to help out

**Review by dcalhoun — APPROVED** [review]

**Comment by dcalhoun** [comment]
Thanks for this!

**Comment by dac09** [comment]
Sorry I never got round to adding the test!

**Comment by dcalhoun** [comment]
> Sorry I never got round to adding the test!

@dac09 No worries. I should've merged it when you first opened and added the test later. Sorry for the delay.

I'll try to publish a release this week.
